GET http://localhost:5195/games

###
GET http://localhost:5195/games/2

###
POST http://localhost:5195/games
Content-Type: application/json

{
  "name": "Game 1",
  "genreId": 5,
  "price": 10.0,
  "releaseDate": "2021-01-01"
}


###
PUT http://localhost:5195/games/10
Content-Type: application/json

{
  "genre": "Updated Genre",
  "price": 19.99,
  "releaseDate": "2023-01-01"
}


###
DELETE http://localhost:5195/games/2